grafana:
  adminPassword: ${GRAFANAPASS}
  defaultDashboardsTimezone: Europe/Berlin
  ingress:
    annotations: 
      #nginx.ingress.kubernetes.io/rewrite-target: /$2
      #nginx.ingress.kubernetes.io/use-regex: "true"
      #nginx.ingress.kubernetes.io/proxy-set-headers: "nginx-headers"
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
    enabled: true
    hosts:
      - grafana.localhost
    path: /
    pathType: Prefix
    ingressClassName: nginx
  
