imagePullSecrets: 
  - name: pgimporter-dockerhub-secret
dockerHubCredentials: "${DOCKERCONFIGJSON}"
ingress:
  enabled: true
  className: "nginx"
  hosts:
    - host: pgimporter.localhost
      paths:
        - path: /
          pathType: Prefix