# ->=> gets the config https://k3d.io/v5.4.1/usage/configfile/ <=<-
apiVersion: k3d.io/v1alpha5
kind: Simple
metadata:
  name: ${CLUSTER}
servers: 3 # same as `--servers 3`
agents: 1 # same as `--agents 1`
image: rancher/k3s:v1.32.4-k3s1
ports:
  - port: ${HTTPPORT}:80
    nodeFilters:
      - loadbalancer
options:
  k3d:
    wait: true
    timeout: "300s" 
    disableImageVolume: false
    disableLoadbalancer: false
  k3s:
    extraArgs:
      - arg: --disable=traefik
        nodeFilters:
          - server:*
  kubeconfig:
    updateDefaultKubeconfig: true
    switchCurrentContext: true
